import { describe, it, expect, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor, within } from '@testing-library/svelte'
import { resetDb } from '../lib/db'
import { go, back, presetButton, presetItem, pickPreset, salva } from '../test/nav'
import App from '../App.svelte'
import { LEG_IDS } from '../lib/regions'
import { addPreset, logPreset } from '../lib/presets'
import { addEntry } from '../lib/entries'
import { resetLog, more, body, menuOfPresets } from '../test/log'

let db: ReturnType<typeof resetDb>
beforeEach(() => {
  db = resetLog()
})

describe('Preset sheet and switched-off symptoms', () => {
  it('asks only what is on, and saves a layer whose every ask is off as a place (#115)', async () => {
    await addPreset({ name: 'Gambe', layers: [{ regions: LEG_IDS, asks: ['pain', 'swelling'] }, { regions: ['224'], asks: ['swelling'] }], kind: 'chronic' })
    await db.symptoms.update('swelling', { enabled: false })
    render(App)
    await screen.findByRole('slider', { name: 'Dolore' })
    await pickPreset(/^Gambe/)
    const sheet = await screen.findByRole('dialog', { name: 'Gambe' })
    expect(within(sheet).getAllByRole('slider').map((s) => s.getAttribute('aria-label'))).toEqual(['Dolore'])
    await fireEvent.input(within(sheet).getByRole('slider', { name: 'Dolore' }), { target: { value: '4' } })
    await fireEvent.click(within(sheet).getByRole('button', { name: 'Salva' }))
    await waitFor(async () => expect(await db.entries.count()).toBe(1))
    const [e] = await db.entries.toArray()
    expect(e.layers.map((l) => l.readings)).toEqual([{ pain: 4 }, {}])
  }, 10_000)
})

describe('Presets', () => {
  it('the Preset dropdown offers a new preset before any exists; the form is its shape, the chips say what it asks, the form stays as it was', async () => {
    render(App)
    // Before any preset, the dropdown holds only the way to make one.
    expect(presetButton()).toHaveAccessibleName('Preset')
    expect(within(await menuOfPresets()).getAllByRole('menuitem')).toHaveLength(1)
    await fireEvent.keyDown(await menuOfPresets(), { key: 'Escape' })
    await fireEvent.click(screen.getByRole('button', { name: 'Gambe' }))
    await more()
    await fireEvent.input(await screen.findByRole('slider', { name: 'Gonfiore' }), { target: { value: '3' } })
    await fireEvent.click(await screen.findByRole('button', { name: 'Impacco caldo' }))
    await pickPreset('Nuovo preset')
    const form = await screen.findByRole('dialog', { name: 'Nuovo preset' })
    // Prefilled from the log form: the legs, pain and swelling asked, no time, tags, sliders or note.
    expect(within(form).getByRole('button', { name: 'Gambe' })).toHaveAttribute('aria-pressed', 'true')
    expect(within(form).getByRole('button', { name: 'Cronico' })).toHaveAttribute('aria-pressed', 'true')
    const asks = within(form).getByRole('group', { name: 'Chiede' })
    expect(await within(asks).findByRole('button', { name: 'Dolore' })).toHaveAttribute('aria-pressed', 'true')
    expect(within(asks).getByRole('button', { name: 'Gonfiore' })).toHaveAttribute('aria-pressed', 'true')
    expect(within(asks).getByRole('button', { name: 'Rigidità' })).toHaveAttribute('aria-pressed', 'false')
    expect(within(asks).queryByRole('button', { name: 'Ansia' })).not.toBeInTheDocument()
    expect(within(form).queryByRole('button', { name: 'Adesso' })).not.toBeInTheDocument()
    expect(within(form).queryByRole('button', { name: 'Impacco caldo' })).not.toBeInTheDocument()
    expect(within(form).queryByRole('slider')).not.toBeInTheDocument()
    expect(within(form).queryByRole('textbox', { name: 'Note' })).not.toBeInTheDocument()
    // Membership is explicit: a symptom at 0 today can still be asked, one above 0 can be left out.
    await fireEvent.click(within(asks).getByRole('button', { name: 'Rigidità' }))
    await fireEvent.click(within(asks).getByRole('button', { name: 'Gonfiore' }))
    const create = within(form).getByRole('button', { name: 'Crea preset' })
    // Without a name the button stays readable and says what is missing by putting the cursor in the name (#23).
    const name = within(form).getByRole('textbox', { name: 'Nome del preset' })
    expect(create).toBeEnabled()
    await fireEvent.click(create)
    expect(name).toHaveFocus()
    expect(await db.presets.count()).toBe(0)
    await fireEvent.input(name, { target: { value: 'Le gambe' } })
    await fireEvent.click(create)
    expect(await screen.findByText('Preset creato')).toBeInTheDocument()
    await waitFor(() => expect(screen.queryByRole('dialog', { name: 'Nuovo preset' })).not.toBeInTheDocument())
    expect(await db.presets.count()).toBe(1)
    const [p] = await db.presets.toArray()
    expect(p).toMatchObject({ name: 'Le gambe', kind: 'chronic' })
    expect(p.layers).toEqual([{ regions: [...LEG_IDS].sort(), asks: ['pain', 'stiffness'] }])
    // The form is untouched and carries nothing: the preset is made, the log form stays a plain entry (§5.6).
    expect(presetButton()).toHaveAccessibleName('Preset')
    expect(presetButton()).not.toHaveClass('linked')
    const made = await presetItem(/Le gambe/)
    expect(made).toHaveTextContent('mai')
    expect(made).not.toHaveAttribute('aria-current')
    // The + of Nuovo preset is drawn, not typed, so it sits in the middle of its circle.
    expect((await presetItem('Nuovo preset')).querySelector('svg')).not.toBeNull()
    await fireEvent.keyDown(await menuOfPresets(), { key: 'Escape' })
    expect(screen.getByRole('button', { name: 'Impacco caldo' })).toHaveAttribute('aria-pressed', 'true')
    await body()
    expect(screen.getByRole('button', { name: 'Gambe' })).toHaveAttribute('aria-pressed', 'true')
    await salva()
    await waitFor(async () => expect(await db.entries.count()).toBe(1))
    const [e] = await db.entries.toArray()
    expect(e).not.toHaveProperty('presetId')
    expect(e.layers).toEqual([{ regions: [...LEG_IDS].sort(), readings: { pain: 5, swelling: 3 }, tags: ['heat'] }])
    // A reading under the preset comes from its own sheet.
    await pickPreset(/Le gambe/)
    const sheet = await screen.findByRole('dialog', { name: 'Le gambe' })
    await fireEvent.input(within(sheet).getByRole('slider', { name: 'Dolore' }), { target: { value: '4' } })
    await fireEvent.click(within(sheet).getByRole('button', { name: 'Salva' }))
    await waitFor(async () => expect(await presetItem(/Le gambe/)).toHaveTextContent(/^4\s*Le gambe · 0m$/))
  })

  it('zones changed in the preset form stay in the preset: the log form keeps its own, and its Salva files nothing under the new name', async () => {
    render(App)
    await fireEvent.click(screen.getByRole('button', { name: 'Gambe' }))
    await pickPreset('Nuovo preset')
    const form = await screen.findByRole('dialog', { name: 'Nuovo preset' })
    await within(within(form).getByRole('group', { name: 'Chiede' })).findByRole('button', { name: 'Dolore' })
    // In the preset form: the legs out, the arms in.
    await fireEvent.click(within(form).getByRole('button', { name: 'Gambe' }))
    await fireEvent.click(within(form).getByRole('button', { name: 'Braccia' }))
    await fireEvent.input(within(form).getByRole('textbox', { name: 'Nome del preset' }), { target: { value: 'Braccia' } })
    await fireEvent.click(within(form).getByRole('button', { name: 'Crea preset' }))
    await waitFor(async () => expect(await db.presets.count()).toBe(1))
    const [p] = await db.presets.toArray()
    expect(p.layers[0].regions).not.toContain(LEG_IDS[0])
    await waitFor(() => expect(screen.queryByRole('dialog', { name: 'Nuovo preset' })).not.toBeInTheDocument())
    await salva()
    await waitFor(async () => expect(await db.entries.count()).toBe(1))
    const [e] = await db.entries.toArray()
    expect(e).not.toHaveProperty('presetId')
    expect(e.layers[0].regions).toEqual([...LEG_IDS].sort())
  })

  it('a preset whose last sample read nothing shows no level in the dropdown, not a 0 (#114)', async () => {
    const p = await addPreset({ name: 'Solo dove', layers: [{ regions: ['152'], asks: [] }], kind: 'chronic' })
    await logPreset(p, [{}])
    render(App)
    const item = await presetItem(/Solo dove/)
    await waitFor(() => expect(item).not.toHaveTextContent('mai'))
    expect(item.querySelector('.dot')).toHaveTextContent('–')
  })

  it('undo on the created preset removes it; the form never carried it', async () => {
    render(App)
    await fireEvent.click(screen.getByRole('button', { name: 'Gambe' }))
    await pickPreset('Nuovo preset')
    const form = await screen.findByRole('dialog', { name: 'Nuovo preset' })
    await within(within(form).getByRole('group', { name: 'Chiede' })).findByRole('button', { name: 'Dolore' })
    await fireEvent.input(within(form).getByRole('textbox', { name: 'Nome del preset' }), { target: { value: 'Le gambe' } })
    await fireEvent.keyDown(within(form).getByRole('textbox', { name: 'Nome del preset' }), { key: 'Enter' })
    await waitFor(async () => expect(await db.presets.count()).toBe(1))
    await fireEvent.click(await screen.findByRole('button', { name: 'Annulla' }))
    await waitFor(async () => expect(await db.presets.count()).toBe(0))
    expect(within(await menuOfPresets()).getAllByRole('menuitem')).toHaveLength(1)
    expect(screen.getByRole('button', { name: 'Gambe' })).toHaveAttribute('aria-pressed', 'true')
  })

  it('an empty form gives an empty shape: no location, pain asked; the time chip is not part of it', async () => {
    await addEntry({ at: '2026-09-02T10:00:00.000Z', layers: [{ regions: LEG_IDS, readings: { pain: 4, swelling: 2 }, tags: ['heat'] }], note: 'x' })
    render(App)
    await more()
    await fireEvent.click(screen.getByRole('button', { name: '1h fa' }))
    await pickPreset('Nuovo preset')
    const form = await screen.findByRole('dialog', { name: 'Nuovo preset' })
    expect(within(form).getByText('Nessuna zona: tocca la figura')).toBeInTheDocument()
    expect(within(form).getByRole('button', { name: 'Gambe' })).toHaveAttribute('aria-pressed', 'false')
    const asks = within(form).getByRole('group', { name: 'Chiede' })
    expect(await within(asks).findByRole('button', { name: 'Dolore' })).toHaveAttribute('aria-pressed', 'true')
    expect(within(asks).getByRole('button', { name: 'Gonfiore' })).toHaveAttribute('aria-pressed', 'false')
    await fireEvent.input(within(form).getByRole('textbox', { name: 'Nome del preset' }), { target: { value: 'Vago' } })
    await fireEvent.click(within(form).getByRole('button', { name: 'Crea preset' }))
    await waitFor(async () => expect(await db.presets.count()).toBe(1))
    const [p] = await db.presets.toArray()
    expect(p).toMatchObject({ name: 'Vago', kind: 'chronic', layers: [{ regions: [], asks: ['pain'] }] })
    expect(screen.getByRole('button', { name: '1h fa' })).toHaveAttribute('aria-pressed', 'true')
  })

  it('creates a preset from a saved entry in the diary; the edit sheet stays open and is not saved', async () => {
    render(App)
    await fireEvent.click(screen.getByRole('button', { name: 'Gambe' }))
    await salva()
    await waitFor(async () => expect(await db.entries.count()).toBe(1))
    await go('Diario')
    await fireEvent.click((await screen.findAllByRole('button', { name: /\d\d:\d\d/ }))[0])
    const edit = await screen.findByRole('dialog', { name: 'Modifica' })
    await fireEvent.click(within(edit).getByRole('button', { name: 'Spalla sx' }))
    await more(within(edit))
    await fireEvent.click(within(edit).getByRole('button', { name: 'Crea preset da questa voce' }))
    const form = await screen.findByRole('dialog', { name: 'Nuovo preset' })
    expect(within(form).getByRole('button', { name: 'Gambe' })).toHaveAttribute('aria-pressed', 'true')
    expect(within(form).getByRole('button', { name: 'Spalla sx' })).toHaveAttribute('aria-pressed', 'true')
    // Escape closes the top sheet only.
    await fireEvent.keyDown(window, { key: 'Escape' })
    await waitFor(() => expect(screen.queryByRole('dialog', { name: 'Nuovo preset' })).not.toBeInTheDocument())
    expect(screen.getByRole('dialog', { name: 'Modifica' })).toBeInTheDocument()
    await fireEvent.click(within(edit).getByRole('button', { name: 'Crea preset da questa voce' }))
    const again = await screen.findByRole('dialog', { name: 'Nuovo preset' })
    await fireEvent.input(within(again).getByRole('textbox', { name: 'Nome del preset' }), { target: { value: 'Le gambe' } })
    await fireEvent.click(within(again).getByRole('button', { name: 'Crea preset' }))
    expect(await screen.findByText('Preset creato')).toBeInTheDocument()
    expect(screen.getByRole('dialog', { name: 'Modifica' })).toBeInTheDocument()
    await waitFor(async () => expect(await db.presets.count()).toBe(1))
    const [p] = await db.presets.toArray()
    expect(p.layers).toEqual([{ regions: [...LEG_IDS, '130', '131'].sort(), asks: ['pain'] }])
    // The entry itself was not saved with the shoulder.
    const [e] = await db.entries.toArray()
    expect(e.layers[0].regions).toEqual([...LEG_IDS].sort())
    await fireEvent.keyDown(window, { key: 'Escape' })
    // The closed sheet gives its history step back after the current task; a back in the same task would spend it.
    await waitFor(() => expect(history.state?.sheet).toBeUndefined())
    await back()
    expect(presetButton()).toHaveAccessibleName('Preset')
    const chip = await presetItem(/Le gambe/)
    expect(chip).toHaveTextContent('mai')
    await fireEvent.click(chip)
    const ps = await screen.findByRole('dialog', { name: 'Le gambe' })
    await fireEvent.input(within(ps).getByRole('slider', { name: 'Dolore' }), { target: { value: '6' } })
    await fireEvent.click(within(ps).getByRole('button', { name: 'Salva' }))
    await waitFor(async () => {
      expect(await db.entries.count()).toBe(2)
      const logged = (await db.entries.toArray()).find((x) => x.presetId)!
      expect(logged.presetId).toBe(p.id)
      expect(logged.layers).toEqual([{ regions: [...LEG_IDS, '130', '131'].sort(), readings: { pain: 6 }, tags: [] }])
    })
    await waitFor(async () => expect(await presetItem(/Le gambe/)).toHaveTextContent(/^6\s*Le gambe · 0m$/))
  })

  it("an episode preset's sheet says it starts one: Inizio over the time, Inizia episodio on the button (#115)", async () => {
    await addPreset({ name: 'Emicrania', layers: [{ regions: ['100'], asks: ['pain'] }], kind: 'episode' })
    await addPreset({ name: 'Schiena', layers: [{ regions: ['224'], asks: ['pain'] }], kind: 'chronic' })
    render(App)
    await pickPreset(/Emicrania/)
    const ep = await screen.findByRole('dialog', { name: 'Emicrania' })
    expect(within(ep).getByRole('group', { name: 'Inizio' })).toBeInTheDocument()
    // Captioned on screen too, as the log's time rows are.
    expect(within(ep).getByText('Inizio')).toBeVisible()
    await fireEvent.input(within(ep).getByRole('slider', { name: 'Dolore' }), { target: { value: '6' } })
    await fireEvent.click(within(ep).getByRole('button', { name: 'Inizia episodio' }))
    await waitFor(async () => expect((await db.entries.toArray()).filter((e) => e.kind === 'episode')).toHaveLength(1))
    // A chronic preset's sheet stays as it was.
    await pickPreset(/Schiena/)
    const ch = await screen.findByRole('dialog', { name: 'Schiena' })
    expect(within(ch).getByRole('group', { name: 'Quando' })).toBeInTheDocument()
    expect(within(ch).getByText('Quando')).toBeVisible()
    expect(within(ch).getByRole('button', { name: 'Salva' })).toBeInTheDocument()
  })

  it('logs a preset at a chosen time: the sheet has the time chips', async () => {
    const p = await addPreset({ name: 'Schiena', layers: [{ regions: ['224'], asks: ['pain'] }], kind: 'chronic' })
    render(App)
    await pickPreset(/Schiena/)
    const ps = await screen.findByRole('dialog', { name: 'Schiena' })
    expect(within(ps).getByRole('button', { name: 'Adesso' })).toHaveAttribute('aria-pressed', 'true')
    await fireEvent.click(within(ps).getByRole('button', { name: 'Ieri sera' }))
    await fireEvent.input(within(ps).getByRole('slider', { name: 'Dolore' }), { target: { value: '4' } })
    await fireEvent.click(within(ps).getByRole('button', { name: 'Salva' }))
    await waitFor(async () => expect(await db.entries.count()).toBe(1))
    const [e] = await db.entries.toArray()
    expect(e.presetId).toBe(p.id)
    const d = new Date(e.at)
    expect(d.getHours()).toBe(22)
    expect(d.getDate()).toBe(new Date(Date.now() - 86_400_000).getDate())
    // The chip says how long ago the last sample was, so a backdated one reads as such.
    await waitFor(async () => expect(await presetItem(/Schiena/)).toHaveTextContent(/· (\d+h|\d+g( \d+h)?)$/))
    // The next opening starts from now again.
    await pickPreset(/Schiena/)
    const again = await screen.findByRole('dialog', { name: 'Schiena' })
    expect(within(again).getByRole('button', { name: 'Adesso' })).toHaveAttribute('aria-pressed', 'true')
  })

  it('the preset sheet starts every slider at 0, whatever was logged before', async () => {
    const p = await addPreset({ name: 'Schiena', layers: [{ regions: ['224'], asks: ['pain', 'swelling'] }], kind: 'chronic' })
    const { logPreset } = await import('../lib/presets')
    await logPreset(p, [{ pain: 3, swelling: 7 }])
    render(App)
    await pickPreset(/Schiena/)
    const ps = await screen.findByRole('dialog', { name: 'Schiena' })
    expect(within(ps).getByRole('slider', { name: 'Dolore' })).toHaveValue('0')
    expect(within(ps).getByRole('slider', { name: 'Gonfiore' })).toHaveValue('0')
  })

  it('a preset asking nothing at all is a one-tap "nothing to report": its sheet has no sliders and records no reading', async () => {
    render(App)
    await fireEvent.click(screen.getByRole('button', { name: 'Gambe' }))
    await pickPreset('Nuovo preset')
    const form = await screen.findByRole('dialog', { name: 'Nuovo preset' })
    const asks = within(form).getByRole('group', { name: 'Chiede' })
    await fireEvent.click(await within(asks).findByRole('button', { name: 'Dolore' }))
    await fireEvent.input(within(form).getByRole('textbox', { name: 'Nome del preset' }), { target: { value: 'Gambe ok' } })
    expect(within(form).getByRole('button', { name: 'Crea preset' })).toBeEnabled()
    await fireEvent.click(within(form).getByRole('button', { name: 'Crea preset' }))
    await waitFor(async () => expect(await db.presets.count()).toBe(1))
    expect((await db.presets.toArray())[0].layers).toEqual([{ regions: [...LEG_IDS].sort(), asks: [] }])
    await pickPreset(/Gambe ok/)
    const ps = await screen.findByRole('dialog', { name: 'Gambe ok' })
    expect(within(ps).queryByRole('slider')).not.toBeInTheDocument()
    await fireEvent.click(within(ps).getByRole('button', { name: 'Salva' }))
    await waitFor(async () => expect(await db.entries.count()).toBe(1))
    expect((await db.entries.toArray())[0].layers).toEqual([{ regions: [...LEG_IDS].sort(), readings: {}, tags: [] }])
  })

  it('a layer asking nothing is kept: Crea stays enabled, the sheet shows it no sliders', async () => {
    render(App)
    await fireEvent.click(screen.getByRole('button', { name: 'Gambe' }))
    await fireEvent.click(screen.getByRole('button', { name: 'Altra zona' }))
    await fireEvent.click(screen.getByRole('button', { name: 'Mente' }))
    await pickPreset('Nuovo preset')
    const form = await screen.findByRole('dialog', { name: 'Nuovo preset' })
    // Chiede follows the layer: the mind layer, current, offers the mind symptoms and asks nothing yet.
    const asks = within(form).getByRole('group', { name: 'Chiede' })
    expect(await within(asks).findByRole('button', { name: 'Nebbia mentale' })).toHaveAttribute('aria-pressed', 'false')
    expect(within(asks).queryByRole('button', { name: 'Dolore' })).not.toBeInTheDocument()
    await fireEvent.click(form.querySelectorAll<HTMLButtonElement>('.chips.areas .area')[0])
    expect(within(asks).getByRole('button', { name: 'Dolore' })).toHaveAttribute('aria-pressed', 'true')
    await fireEvent.input(within(form).getByRole('textbox', { name: 'Nome del preset' }), { target: { value: 'Gambe e testa' } })
    await fireEvent.click(within(form).getByRole('button', { name: 'Crea preset' }))
    await waitFor(async () => expect(await db.presets.count()).toBe(1))
    const [p] = await db.presets.toArray()
    expect(p.layers).toEqual([{ regions: [...LEG_IDS].sort(), asks: ['pain'] }, { regions: ['mind'], asks: [] }])
    // Logging from the preset's own sheet.
    await pickPreset(/Gambe e testa/)
    const ps = await screen.findByRole('dialog', { name: 'Gambe e testa' })
    const chips = ps.querySelectorAll<HTMLButtonElement>('.chips.layers .area')
    expect(chips).toHaveLength(2)
    await fireEvent.input(within(ps).getByRole('slider', { name: 'Dolore' }), { target: { value: '2' } })
    await fireEvent.click(chips[1])
    expect(within(ps).queryByRole('slider')).not.toBeInTheDocument()
    await fireEvent.click(within(ps).getByRole('button', { name: 'Salva' }))
    await waitFor(async () => expect(await db.entries.count()).toBe(1))
    expect((await db.entries.toArray())[0].layers).toEqual([{ regions: [...LEG_IDS].sort(), readings: { pain: 2 }, tags: [] }, { regions: ['mind'], readings: {}, tags: [] }])
    // The log form, linked to nothing, stays as it was.
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.getByRole('button', { name: 'Azzera' })).toBeEnabled()
    expect(presetButton()).toHaveAccessibleName('Preset')
  })

  it('a preset with several layers: the sheet asks each layer its own sliders and saves each its own levels', async () => {
    const p = await addPreset({ name: 'Gambe e spalla', layers: [{ regions: LEG_IDS, asks: ['pain', 'swelling'] }, { regions: ['130', '131'], asks: ['pain'] }], kind: 'chronic' })
    render(App)
    await pickPreset(/Gambe e spalla/)
    const ps = await screen.findByRole('dialog', { name: 'Gambe e spalla' })
    const chips = () => ps.querySelectorAll<HTMLButtonElement>('.chips.layers .area')
    await waitFor(() => expect(chips()).toHaveLength(2))
    expect(chips()[0]).toHaveAttribute('aria-pressed', 'true')
    expect(within(ps).getByRole('slider', { name: 'Dolore' })).toHaveValue('0')
    await fireEvent.input(within(ps).getByRole('slider', { name: 'Dolore' }), { target: { value: '5' } })
    await fireEvent.input(within(ps).getByRole('slider', { name: 'Gonfiore' }), { target: { value: '6' } })
    await fireEvent.click(chips()[1])
    expect(chips()[1]).toHaveAttribute('aria-pressed', 'true')
    expect(within(ps).queryByRole('slider', { name: 'Gonfiore' })).not.toBeInTheDocument()
    await fireEvent.input(within(ps).getByRole('slider', { name: 'Dolore' }), { target: { value: '2' } })
    await fireEvent.click(within(ps).getByRole('button', { name: 'Salva' }))
    await waitFor(async () => expect(await db.entries.count()).toBe(1))
    const [e] = await db.entries.toArray()
    expect(e.presetId).toBe(p.id)
    expect(e.layers).toEqual([
      { regions: [...LEG_IDS].sort(), readings: { pain: 5, swelling: 6 }, tags: [] },
      { regions: ['130', '131'], readings: { pain: 2 }, tags: [] },
    ])
    // The next opening starts from 0 again.
    await pickPreset(/Gambe e spalla/)
    const again = await screen.findByRole('dialog', { name: 'Gambe e spalla' })
    expect(within(again).getByRole('slider', { name: 'Gonfiore' })).toHaveValue('0')
  })
})
