// Writes src/lib/figures.ts from the CHOIR polygons in scripts/choir/ (see the README there).
// Usage: node scripts/choir.mjs
// The two silhouettes are kept as-is, keyed by CHOIR segment code; the female numbering of
// 112–117 is rewritten to the male one so a code means the same segment on both figures.
import { readFileSync, writeFileSync } from 'node:fs'

const FEMALE_TO_MALE = { 112: 116, 113: 117, 114: 112, 115: 113, 116: 114, 117: 115 }

function load(name, recode) {
  const rows = readFileSync(new URL(`./choir/${name}.csv`, import.meta.url), 'utf8').trim().split('\n').slice(1)
  const polys = {}
  for (const line of rows) {
    const [id, x, y] = line.replace(/"/g, '').split(',').map(Number)
    const code = recode ? (FEMALE_TO_MALE[id] ?? id) : id
    ;(polys[code] ??= []).push([x, y])
  }
  return polys
}

const FIGURES = {
  female: { front: load('female_front', true), back: load('female_back', true) },
  male: { front: load('male_front', false), back: load('male_back', false) },
}
const bbox = (polys) => {
  const pts = Object.values(polys).flat()
  return { w: Math.max(...pts.map((p) => p[0])), h: Math.max(...pts.map((p) => p[1])) }
}
const out = `// Generated by scripts/choir.mjs from scripts/choir/*.csv (CHOIRBM, MIT; see the README there). Do not edit by hand.

export type FigureId = 'female' | 'male'
export type FigureView = 'front' | 'back'

/** Segment polygons of the CHOIR body map, keyed by CHOIR code (male numbering on both figures), in the package's units. */
export const FIGURES: Record<FigureId, Record<FigureView, Record<string, [number, number][]>>> = ${JSON.stringify(FIGURES)}

/** Extent of each figure, for a viewBox. */
export const FIGURE_SIZE: Record<FigureId, { w: number; h: number }> = ${JSON.stringify({ female: bbox({ ...FIGURES.female.front, ...FIGURES.female.back }), male: bbox({ ...FIGURES.male.front, ...FIGURES.male.back }) })}
`
writeFileSync(new URL('../src/lib/figures.ts', import.meta.url), out)
for (const f of ['female', 'male']) for (const v of ['front', 'back']) console.log(f, v, Object.keys(FIGURES[f][v]).length, 'segments,', Object.values(FIGURES[f][v]).flat().length, 'points')
